import { resolve } from 'path'
import theme from '@nuxt/content-theme-docs'

export default theme({
	content: {
		dir: 'docs',
		// since the MarkDown files will be generated by docgen cli
		// editing them will be overwritten as soon as the next generation
		liveEdit: false,
		markdown: {
			// transform fenced code blocks into VueLive
			remarkPlugins: ['remark-plugin-vue-live']
		}
	},
	components:{
		global: true,
		dirs: ['./components']
	},
	router: {
		base: '/docgen-nuxt/'
	},
	// force generate to create a index.html
	generate: {
		routes: ['/']
	},
	build: {
		extend(config) {
			// make template coiler available at runtime
			config.resolve.alias['vue$'] = 'vue/dist/vue.esm.js'
		}
	},
	plugins: [
		// register the vue-live component
		resolve(__dirname, './plugins/vue-live.js'),
	]
})
